.DEFINE TRUE    1
.DEFINE FALSE   0

.DEFINE JOYPAD_P1_UP    0
.DEFINE JOYPAD_P1_DOWN  1
.DEFINE JOYPAD_P1_LEFT  2
.DEFINE JOYPAD_P1_RIGHT 3
.DEFINE JOYPAD_P1_B1    4
.DEFINE JOYPAD_P1_B2    5

.DEFINE GOING_UP        1
.DEFINE GOING_DOWN      2
.DEFINE GOING_LEFT      3
.DEFINE GOING_RIGHT     4

.DEFINE DEFAULT_LIFE    3
.DEFINE MAX_LIFE        3
.DEFINE APPLE           255
.DEFINE SNAKE_DEFAULT_SPEED     $1C
.DEFINE SNAKE_MAX_SPEED $08
.DEFINE SNAKE_HARD_SPEED        $06

.DEFINE NORMAL_MODE_POINT       25
.DEFINE HARD_MODE_POINT         50

.DEFINE UP_BORDER       -1
.DEFINE DOWN_BORDER     16
.DEFINE LEFT_BORDER     -1
.DEFINE RIGHT_BORDER    16
